package com.kwon.new_mbti_community.Contain

import com.kwon.new_mbti_community.Contain.Define.Companion.SIGNUP_SUCCESS

enum class ApiStatus(val code:String,val comment:String) {
    SUCCESS_CREATE("S0001",SIGNUP_SUCCESS),
    SUCCESS_UPDATE("S0002",SIGNUP_SUCCESS),
    SUCCESS_DELETE("S0003",SIGNUP_SUCCESS),
    SUCCESS("S0004",SIGNUP_SUCCESS),
    SUCCESS_LOGIN("S0008",SIGNUP_SUCCESS),

    ERROR_KEY("E0002",SIGNUP_SUCCESS),
    ERROR_OVERLAP_NICKNAME("E0003",SIGNUP_SUCCESS),
    ERROR_OVERLAP_USERNAME("E0004",SIGNUP_SUCCESS),
    FAIL_LOGIN("E0005",SIGNUP_SUCCESS)

}